<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>BackupApp.Platform.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BackupApp.Domain\BackupApp.Domain.csproj" />
  </ItemGroup>
</Project>
